### ISSUE TITLE
docs: write a contributing guide.

### ISSUE THREAD

**Issue by a1eaiactaest** [a1eaiactaest/rere#34]
Example of that: 
https://mozillascience.github.io/working-open-workshop/contributing/
and 
https://github.com/github/docs/blob/main/CONTRIBUTING.md

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue. Do you have any particular format in mind for PR or commits?

**Comment by a1eaiactaest** [comment]
@Mount-Blanc  Actually this should be closed since a1f552c75b366c4a9ff73062f2595a7ee27a014a. Go ahead and read our [contributing guide](https://github.com/a1eaiactaest/rere/blob/main/docs/CONTRIBUTING.md). Any help is appriciated.
